### ISSUE TITLE
[ES API] Besoin de pouvoir donner des poids à notre recherche ES

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/kinetix#14]
Notre besoin est de pouvoir ouvrir l'API de recherche pour donner des poids différents aux critères de recherche : par exemple donner plus de poids au code qu'au libellé.

Il faut par ailleurs pouvoir rechercher sur plusieurs champs textuels. Actuellement, la recherche se fait sur un unique champ.

**Comment by durandx** [comment]
Corrigé sur develop
