### ISSUE TITLE
[ModGen] alias non connu --> le nom de la classe n'est pas affiché dans le message d'erreur

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/kinetix#16]
![image](https://user-images.githubusercontent.com/5349745/41462601-a776ac9c-7093-11e8-906d-2a6655193496.png)

Impossible de savoir sur quel classe l'erreur est levée.

**Comment by durandx** [comment]
Fixed in master in commit : bc703e9d03efa46d44d206b5f4bd17a45840475c
