### ISSUE TITLE
[Search] Filter should be able to be text based search

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/kinetix#18]
Today Fitler columns can only be term search and not text search

-> type of search/matching/indexing should be decoupled from the Search/Id/Security attributes

**Comment by durandx** [comment]
Just a remark : Please explain the problematic Use Case before pointing the technical Issue.

**Comment by c3dr0x** [comment]
When using the advanced filter component of focus, we specify filters on specific fields. I need to use the text search feature on those specific fields (as with Search field type) and not a term comparison.

![image](https://user-images.githubusercontent.com/1591017/41982640-38b065bc-7a2c-11e8-9b75-7365cd516ce6.png)

**Comment by durandx** [comment]
Fixed in develop
