### ISSUE TITLE
[Notification Center] Needs an api to remove notifications by uuids

### ISSUE THREAD

**Issue by TomGallon** [KleeGroup/kinetix#2]
A new API which allows to remove notifications by uuids is missing in Kinetix FMK.
@NPi2Loup is currently adding it in Vertigo.

Could you please add it in Kinetix ?
It is required by a project.

Thks.

**Comment by durandx** [comment]
The Notification API has been added in Kinetix (commit c20a022a7b718ceef3504be719c46ef67e56b392) with the fix
